import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Article from '../models/Article';
import User from '../models/User';

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/luminary_magazine';

const generateContent = (title: string, paragraphs: number = 6): string => {
    const lorem = [
        `<p>The world of ${title.split(' ').slice(-2).join(' ').toLowerCase()} has undergone a seismic transformation in recent years. What once seemed like distant speculation has now become the pulsating center of our cultural and technological moment. Experts across disciplines are converging on a singular conclusion: we are living through one of history's most consequential inflection points.</p>`,
        `<p>To understand the full weight of this shift, we need to look at the data with fresh eyes. Studies conducted across leading research institutions have consistently shown that adoption rates are accelerating at speeds that far outpace historical precedent. The implications for individuals, businesses, and governments alike are profound and far-reaching.</p>`,
        `<p>"We've never seen anything quite like this," says Dr. Elena Marchetti, a professor at the Institute for Advanced Study. "The convergence of multiple exponential trends is creating feedback loops that amplify change in ways that are genuinely difficult to model, let alone predict." Her research team has been documenting these dynamics for over a decade, and even they were caught off guard by the recent acceleration.</p>`,
        `<p>The human dimension of this story is equally compelling. Behind every data point lies a community being reshaped, a worker whose skills are being redefined, a family navigating choices their parents could never have imagined. The social fabric is being rewoven in real time, and the patterns that emerge will define our collective future for generations.</p>`,
        `<p>Critics, of course, urge caution. Not every promised revolution delivers on its early hype, and history is littered with technologies that promised everything and delivered far less. The dot-com era, the genomics revolution, the smart city movement — each generated enormous excitement before settling into a more modest, if still significant, role in everyday life.</p>`,
        `<p>Yet something feels different this time. The convergence of artificial intelligence, biotechnology, renewable energy, and advanced materials science is creating a combinatorial explosion of possibility that is difficult to dismiss. Unlike previous waves of innovation that operated largely in isolation, these technologies are feeding into each other, creating emergent capabilities that no single discipline could have produced alone.</p>`,
        `<p>What does this mean for you, the reader, standing at this crossroads? The honest answer is that no one knows for certain. But the historical record suggests that those who engage thoughtfully with transformative change — neither blindly embracing nor reflexively rejecting it — tend to navigate inflection points most successfully. The goal is not to predict the future but to build the cognitive and social infrastructure to adapt to whatever it brings.</p>`,
        `<p>As we close this examination, one thing remains clear: the decisions made in the next few years will echo for decades. The choices about governance, access, ethics, and distribution of benefits are not technical questions with technical answers. They are fundamentally human questions that require human wisdom, democratic deliberation, and an unflinching commitment to the common good. The conversation has never been more urgent.</p>`,
    ];
    return lorem.slice(0, Math.max(4, paragraphs)).join('\n');
};

const articles = [
    // ===== TECHNOLOGY (6 articles, 3 premium) =====
    {
        title: 'The Quiet Revolution: How Edge Computing Is Rewriting the Rules of the Internet',
        slug: 'edge-computing-revolution',
        coverImage: 'https://picsum.photos/seed/edge-computing/1200/630',
        excerpt: 'Far from the cloud hyperscalers and their gleaming data centers, a different kind of computing revolution is unfolding at the periphery of our networks.',
        content: generateContent('Edge Computing Revolution', 8),
        author: 'Marcus Heidegger',
        category: 'Technology',
        tags: ['edge computing', 'networking', 'infrastructure', 'cloud'],
        isPremium: false,
        publishDate: new Date('2024-06-10'),
        readingTimeMins: 7,
    },
    {
        title: 'Inside the Neural Architecture Search That Could End Deep Learning as We Know It',
        slug: 'neural-architecture-search-deep-learning',
        coverImage: 'https://picsum.photos/seed/neural-arch/1200/630',
        excerpt: 'AutoML and neural architecture search are advancing so quickly that human-designed networks may soon be obsolete. We went inside the labs to find out.',
        content: generateContent('Neural Architecture Search', 8),
        author: 'Priya Subramaniam',
        category: 'Technology',
        tags: ['AI', 'machine learning', 'AutoML', 'deep learning'],
        isPremium: true,
        publishDate: new Date('2024-06-05'),
        readingTimeMins: 9,
    },
    {
        title: 'Quantum Supremacy Revisited: What Google\'s Latest Milestone Actually Proves',
        slug: 'quantum-supremacy-revisited',
        coverImage: 'https://picsum.photos/seed/quantum-comp/1200/630',
        excerpt: 'A year after the landmark announcement, we examine the nuanced reality of quantum advantage and what the roadmap to practical quantum computing actually looks like.',
        content: generateContent('Quantum Computing', 8),
        author: 'Leon Abramowitz',
        category: 'Technology',
        tags: ['quantum computing', 'Google', 'physics', 'computing'],
        isPremium: false,
        publishDate: new Date('2024-05-20'),
        readingTimeMins: 8,
    },
    {
        title: 'The Privacy Paradox: Why Differential Privacy Is Harder Than It Looks',
        slug: 'differential-privacy-paradox',
        coverImage: 'https://picsum.photos/seed/privacy-data/1200/630',
        excerpt: 'Every major tech company now claims to use differential privacy. But the gap between the theory and practice is wider than most people realize.',
        content: generateContent('Differential Privacy', 8),
        author: 'Ananya Krishnan',
        category: 'Technology',
        tags: ['privacy', 'data science', 'security', 'cryptography'],
        isPremium: true,
        publishDate: new Date('2024-05-12'),
        readingTimeMins: 10,
    },
    {
        title: 'Open Source AI: The Movement That\'s Democratizing Machine Intelligence',
        slug: 'open-source-ai-democratizing',
        coverImage: 'https://picsum.photos/seed/opensource-ai/1200/630',
        excerpt: 'From Llama to Mistral, the open-source AI ecosystem is maturing fast. We explore what this means for researchers, startups, and the future of AI governance.',
        content: generateContent('Open Source AI', 8),
        author: 'Zara Okonkwo',
        category: 'Technology',
        tags: ['AI', 'open source', 'LLM', 'democratization'],
        isPremium: false,
        publishDate: new Date('2024-04-28'),
        readingTimeMins: 6,
    },
    {
        title: 'The Semiconductor Decade: How the Chip Wars Will Shape the Next Fifty Years',
        slug: 'semiconductor-decade-chip-wars',
        coverImage: 'https://picsum.photos/seed/semiconductor/1200/630',
        excerpt: 'Control over semiconductor manufacturing has become the defining geopolitical contest of our era. The stakes couldn\'t be higher.',
        content: generateContent('Semiconductor Wars', 8),
        author: 'James Thornton-Reid',
        category: 'Technology',
        tags: ['semiconductors', 'geopolitics', 'manufacturing', 'supply chain'],
        isPremium: true,
        publishDate: new Date('2024-04-15'),
        readingTimeMins: 11,
    },

    // ===== CULTURE (6 articles, 3 premium) =====
    {
        title: 'The New Aesthetic: How a Generation of Artists Is Using AI as Their Canvas',
        slug: 'ai-art-new-aesthetic',
        coverImage: 'https://picsum.photos/seed/ai-art-culture/1200/630',
        excerpt: 'A wave of digital artists is using generative AI not as a shortcut, but as a radical new medium for expression. We meet the creators defining the aesthetic of tomorrow.',
        content: generateContent('AI Art and Culture', 8),
        author: 'Isabelle Fontaine',
        category: 'Culture',
        tags: ['art', 'AI', 'creativity', 'digital culture'],
        isPremium: false,
        publishDate: new Date('2024-06-08'),
        readingTimeMins: 8,
    },
    {
        title: 'Longreads in the Age of Reels: The Surprising Resurgence of Long-Form Writing',
        slug: 'longform-writing-resurgence',
        coverImage: 'https://picsum.photos/seed/longform-writing/1200/630',
        excerpt: 'Against all conventional wisdom, long-form journalism and essays are finding massive new audiences online. What does this tell us about what readers truly want?',
        content: generateContent('Longform Writing', 8),
        author: 'Samuel Adeyemi',
        category: 'Culture',
        tags: ['journalism', 'writing', 'media', 'reading'],
        isPremium: true,
        publishDate: new Date('2024-06-01'),
        readingTimeMins: 7,
    },
    {
        title: 'The Architecture of Belonging: How Cities Are Redesigning Public Space',
        slug: 'cities-public-space-design',
        coverImage: 'https://picsum.photos/seed/public-space/1200/630',
        excerpt: 'From Barcelona\'s "superblocks" to Seoul\'s restored Cheonggyecheon stream, urban designers are reimagining the city as a fundamentally human space.',
        content: generateContent('City Design Public Space', 8),
        author: 'Maya Delacroix',
        category: 'Culture',
        tags: ['architecture', 'urban design', 'cities', 'community'],
        isPremium: false,
        publishDate: new Date('2024-05-25'),
        readingTimeMins: 9,
    },
    {
        title: 'The Streaming Plateau: Why the Content Wars Are Entering Their Final, Brutal Phase',
        slug: 'streaming-plateau-content-wars',
        coverImage: 'https://picsum.photos/seed/streaming-media/1200/630',
        excerpt: 'Hollywood\'s great streaming experiment is approaching a reckoning. The era of infinite content budgets is over — and the casualties are only beginning.',
        content: generateContent('Streaming Media Industry', 8),
        author: 'Nathan Blackwood',
        category: 'Culture',
        tags: ['streaming', 'Hollywood', 'media', 'entertainment'],
        isPremium: true,
        publishDate: new Date('2024-05-18'),
        readingTimeMins: 8,
    },
    {
        title: 'Language in Motion: The Linguists Mapping the Real-Time Evolution of English',
        slug: 'language-evolution-linguistics',
        coverImage: 'https://picsum.photos/seed/language-culture/1200/630',
        excerpt: 'Social media is accelerating language change in ways that are baffling — and thrilling — scholars. A new generation of computational linguists is trying to keep up.',
        content: generateContent('Language Linguistics Culture', 8),
        author: 'Sofia Chen-Watanabe',
        category: 'Culture',
        tags: ['linguistics', 'language', 'social media', 'culture'],
        isPremium: false,
        publishDate: new Date('2024-05-08'),
        readingTimeMins: 6,
    },
    {
        title: 'The Authenticity Economy: Why \'Real\' Has Become the Most Valuable Currency in Media',
        slug: 'authenticity-economy-media',
        coverImage: 'https://picsum.photos/seed/authenticity/1200/630',
        excerpt: 'From raw, unfiltered podcasts to confessional newsletters, audiences are fleeing polish for something that feels genuine. We examine the cultural forces behind this seismic shift.',
        content: generateContent('Authenticity Media Economy', 8),
        author: 'Chloe Winterbourne',
        category: 'Culture',
        tags: ['media', 'authenticity', 'podcasts', 'culture'],
        isPremium: true,
        publishDate: new Date('2024-04-22'),
        readingTimeMins: 10,
    },

    // ===== SCIENCE (6 articles, 3 premium) =====
    {
        title: 'The Plastisphere: Scientists Are Discovering an Entire Ecosystem Living on Ocean Plastic',
        slug: 'plastisphere-ocean-ecosystem',
        coverImage: 'https://picsum.photos/seed/ocean-plastic/1200/630',
        excerpt: 'Microbes, algae, and invertebrates have colonized our plastic waste, creating a novel biome with unpredictable ecological consequences. Scientists are racing to understand it.',
        content: generateContent('Ocean Plastic Ecosystem', 8),
        author: 'Dr. Rosa Alvarez-Mendes',
        category: 'Science',
        tags: ['ocean', 'ecology', 'plastic', 'microbiology'],
        isPremium: false,
        publishDate: new Date('2024-06-12'),
        readingTimeMins: 9,
    },
    {
        title: 'Psychedelic Medicine\'s Long Road to the Clinic: What the New Research Actually Shows',
        slug: 'psychedelic-medicine-clinical-research',
        coverImage: 'https://picsum.photos/seed/psychedelic-medicine/1200/630',
        excerpt: 'After decades in the scientific wilderness, psilocybin, MDMA, and ketamine are showing genuine promise for treatment-resistant conditions. Here\'s where the science stands.',
        content: generateContent('Psychedelic Medicine Research', 8),
        author: 'Dr. Alistair McGregor',
        category: 'Science',
        tags: ['medicine', 'psychiatry', 'psychedelics', 'mental health'],
        isPremium: true,
        publishDate: new Date('2024-06-03'),
        readingTimeMins: 11,
    },
    {
        title: 'The Second Brain: New Research on the Gut-Mind Connection Is Upending Neuroscience',
        slug: 'gut-brain-connection-neuroscience',
        coverImage: 'https://picsum.photos/seed/gut-brain/1200/630',
        excerpt: 'The enteric nervous system contains nearly as many neurons as the spinal cord. Understanding it may hold the key to treating everything from depression to Parkinson\'s disease.',
        content: generateContent('Gut Brain Neuroscience', 8),
        author: 'Dr. Yuki Tanaka',
        category: 'Science',
        tags: ['neuroscience', 'gut health', 'microbiome', 'medicine'],
        isPremium: false,
        publishDate: new Date('2024-05-22'),
        readingTimeMins: 8,
    },
    {
        title: 'Dark Energy\'s Uncertain Future: The Cosmological Constant Problem Is Getting Stranger',
        slug: 'dark-energy-cosmological-constant',
        coverImage: 'https://picsum.photos/seed/dark-energy/1200/630',
        excerpt: 'New data from the DESI survey is challenging our most fundamental assumptions about the nature of dark energy — and potentially about the ultimate fate of the universe.',
        content: generateContent('Dark Energy Cosmology', 8),
        author: 'Dr. Viktor Petrov',
        category: 'Science',
        tags: ['cosmology', 'dark energy', 'physics', 'universe'],
        isPremium: true,
        publishDate: new Date('2024-05-15'),
        readingTimeMins: 10,
    },
    {
        title: 'The Epigenetics Revolution: How Your Environment Rewrites Your Genetic Code',
        slug: 'epigenetics-revolution-genetic-code',
        coverImage: 'https://picsum.photos/seed/epigenetics/1200/630',
        excerpt: 'Epigenetics is dissolving the boundary between nature and nurture. The implications for medicine, personal responsibility, and social policy are immense.',
        content: generateContent('Epigenetics Genetics Environment', 8),
        author: 'Dr. Nadia Al-Rashid',
        category: 'Science',
        tags: ['genetics', 'epigenetics', 'biology', 'medicine'],
        isPremium: false,
        publishDate: new Date('2024-05-04'),
        readingTimeMins: 7,
    },
    {
        title: 'Engineering Photosynthesis: The Scientists Hack That Could Feed Eight Billion People',
        slug: 'engineering-photosynthesis-food-security',
        coverImage: 'https://picsum.photos/seed/photosynthesis/1200/630',
        excerpt: 'Natural photosynthesis is remarkably inefficient. A global research consortium believes they can improve it — and in doing so, transform agriculture on a planetary scale.',
        content: generateContent('Photosynthesis Engineering Food', 8),
        author: 'Dr. Chidi Okonjo',
        category: 'Science',
        tags: ['agriculture', 'biotechnology', 'food security', 'plant biology'],
        isPremium: true,
        publishDate: new Date('2024-04-18'),
        readingTimeMins: 9,
    },

    // ===== BUSINESS (6 articles, 3 premium) =====
    {
        title: 'The Founder Mode Fallacy: Why Charismatic Leadership Is Destroying Perfectly Good Companies',
        slug: 'founder-mode-leadership-fallacy',
        coverImage: 'https://picsum.photos/seed/founder-mode/1200/630',
        excerpt: 'The cult of the visionary founder has never been more powerful — or more dangerous. We examine the growing body of evidence that great founders often make terrible CEOs.',
        content: generateContent('Founder Leadership Business', 8),
        author: 'Rachel Pemberton',
        category: 'Business',
        tags: ['leadership', 'startups', 'management', 'founders'],
        isPremium: false,
        publishDate: new Date('2024-06-09'),
        readingTimeMins: 8,
    },
    {
        title: 'The New Labor Aristocracy: How AI Is Reshaping the Professional Class',
        slug: 'ai-reshaping-professional-class',
        coverImage: 'https://picsum.photos/seed/labor-ai/1200/630',
        excerpt: 'Automation isn\'t just coming for blue-collar work. The professions — law, medicine, finance — are being restructured from the inside. Who wins and who loses?',
        content: generateContent('AI Labor Professionals', 8),
        author: 'David Warrington',
        category: 'Business',
        tags: ['AI', 'labor', 'automation', 'economy'],
        isPremium: true,
        publishDate: new Date('2024-06-02'),
        readingTimeMins: 10,
    },
    {
        title: 'Deglobalization\'s Hidden Costs: The Numbers Behind the Nationalist Supply Chain Turn',
        slug: 'deglobalization-supply-chain-costs',
        coverImage: 'https://picsum.photos/seed/deglobalization/1200/630',
        excerpt: 'The push to reshore manufacturing and reduce supply chain dependencies sounds sensible. The economic reality is considerably more complicated — and expensive.',
        content: generateContent('Deglobalization Supply Chain', 8),
        author: 'Francesca Morishita',
        category: 'Business',
        tags: ['globalization', 'supply chain', 'economics', 'trade'],
        isPremium: false,
        publishDate: new Date('2024-05-28'),
        readingTimeMins: 9,
    },
    {
        title: 'The B2B SaaS Reckoning: Why the Golden Era of Software Multiples Is Over',
        slug: 'b2b-saas-valuation-reckoning',
        coverImage: 'https://picsum.photos/seed/saas-business/1200/630',
        excerpt: 'For a decade, software-as-a-service commanded premium valuations. Now, as AI compresses margins and competition intensifies, the business model is being pressure-tested like never before.',
        content: generateContent('SaaS Business Valuations', 8),
        author: 'Oliver Hartmann',
        category: 'Business',
        tags: ['SaaS', 'venture capital', 'startups', 'software'],
        isPremium: true,
        publishDate: new Date('2024-05-16'),
        readingTimeMins: 11,
    },
    {
        title: 'The Family Business Paradox: How Dynasties Outlast Startups — and Why They Shouldn\'t',
        slug: 'family-business-dynasty-paradox',
        coverImage: 'https://picsum.photos/seed/family-business/1200/630',
        excerpt: 'Family-controlled companies punch above their weight in longevity but lag in innovation. A new wave of family business researchers thinks they\'ve found out why.',
        content: generateContent('Family Business Dynasty', 8),
        author: 'Amelia Fontana-Ricci',
        category: 'Business',
        tags: ['family business', 'entrepreneurship', 'governance', 'strategy'],
        isPremium: false,
        publishDate: new Date('2024-05-06'),
        readingTimeMins: 7,
    },
    {
        title: 'Inside the Sovereign Wealth Fund Playing the Long Game on Climate',
        slug: 'sovereign-wealth-fund-climate-investing',
        coverImage: 'https://picsum.photos/seed/sovereign-wealth/1200/630',
        excerpt: 'With a $1.8 trillion portfolio, Norway\'s Government Pension Fund is making climate investment decisions that will shape entire industries for decades. We got an inside look.',
        content: generateContent('Sovereign Wealth Climate Finance', 8),
        author: 'Erik Solberg-Hansen',
        category: 'Business',
        tags: ['finance', 'climate', 'investing', 'ESG'],
        isPremium: true,
        publishDate: new Date('2024-04-25'),
        readingTimeMins: 9,
    },

    // ===== HEALTH (6 articles, 3 premium) =====
    {
        title: 'The Sleep Debt Crisis: Why Modern Life Is Running a Neural Deficit We Can\'t Afford',
        slug: 'sleep-debt-neural-crisis',
        coverImage: 'https://picsum.photos/seed/sleep-health/1200/630',
        excerpt: 'Chronic sleep deprivation is quietly degrading the cognitive performance of millions. The neuroscience of what we\'re losing — and how to get it back — is newly urgent.',
        content: generateContent('Sleep Health Neuroscience', 8),
        author: 'Dr. Miriam Osei-Bonsu',
        category: 'Health',
        tags: ['sleep', 'neuroscience', 'health', 'wellness'],
        isPremium: false,
        publishDate: new Date('2024-06-11'),
        readingTimeMins: 8,
    },
    {
        title: 'Rethinking Protein: The Science Behind the Amino Acid Panic — and What You Should Actually Eat',
        slug: 'rethinking-protein-amino-acid-science',
        coverImage: 'https://picsum.photos/seed/protein-health/1200/630',
        excerpt: 'The fitness industry has made protein the center of every nutrition conversation. The science is considerably more nuanced — and the implications for plant-based eaters are significant.',
        content: generateContent('Protein Nutrition Science', 8),
        author: 'Dr. Lena Brandt',
        category: 'Health',
        tags: ['nutrition', 'protein', 'diet', 'science'],
        isPremium: true,
        publishDate: new Date('2024-06-04'),
        readingTimeMins: 9,
    },
    {
        title: 'The Longevity Lab: Inside the Race to Add a Decade to the Human Healthspan',
        slug: 'longevity-lab-healthspan-decade',
        coverImage: 'https://picsum.photos/seed/longevity/1200/630',
        excerpt: 'From senolytics to caloric restriction mimetics, the science of aging is experiencing a renaissance. We visited the labs where researchers are trying to slow the clock.',
        content: generateContent('Longevity Aging Science', 8),
        author: 'Dr. James Harrington',
        category: 'Health',
        tags: ['longevity', 'aging', 'medicine', 'biotechnology'],
        isPremium: false,
        publishDate: new Date('2024-05-24'),
        readingTimeMins: 10,
    },
    {
        title: 'The Mental Health Industrial Complex: Is the Therapy Boom Actually Helping?',
        slug: 'mental-health-therapy-boom-analysis',
        coverImage: 'https://picsum.photos/seed/mental-health/1200/630',
        excerpt: 'App-based therapy, corporate wellness programs, and the destigmatization of mental health have created a massive industry. But outcome data raises uncomfortable questions.',
        content: generateContent('Mental Health Therapy Industry', 8),
        author: 'Dr. Caroline St. James',
        category: 'Health',
        tags: ['mental health', 'therapy', 'wellness', 'psychology'],
        isPremium: true,
        publishDate: new Date('2024-05-14'),
        readingTimeMins: 10,
    },
    {
        title: 'Zone 2 and the Science of Sustainable Fitness for the Time-Starved Professional',
        slug: 'zone-2-fitness-science-professionals',
        coverImage: 'https://picsum.photos/seed/fitness-zone2/1200/630',
        excerpt: 'Low-intensity aerobic exercise done consistently outperforms every other fitness regimen in the long-term data. Why are we all still doing it wrong?',
        content: generateContent('Fitness Exercise Science Health', 8),
        author: 'Sofia Andersen-Holm',
        category: 'Health',
        tags: ['fitness', 'cardio', 'health', 'exercise science'],
        isPremium: false,
        publishDate: new Date('2024-05-02'),
        readingTimeMins: 7,
    },
    {
        title: 'The Microbiome Frontier: Precision Probiotics and the Future of Personalized Nutrition',
        slug: 'microbiome-precision-probiotics-nutrition',
        coverImage: 'https://picsum.photos/seed/microbiome/1200/630',
        excerpt: 'Your gut microbiome is as unique as a fingerprint. A new generation of biotech companies is using this insight to design personalized nutritional interventions with unprecedented specificity.',
        content: generateContent('Microbiome Probiotics Nutrition', 8),
        author: 'Dr. Kenji Yamamoto',
        category: 'Health',
        tags: ['microbiome', 'nutrition', 'probiotics', 'biotechnology'],
        isPremium: true,
        publishDate: new Date('2024-04-20'),
        readingTimeMins: 9,
    },
];

async function seed() {
    try {
        await mongoose.connect(MONGODB_URI);
        console.log('✅ Connected to MongoDB');

        await Article.deleteMany({});
        console.log('🗑️  Cleared existing articles');

        await Article.insertMany(articles);
        console.log(`✅ Seeded ${articles.length} articles`);

        console.log('\n📊 Summary:');
        const total = await Article.countDocuments();
        const premium = await Article.countDocuments({ isPremium: true });
        const free = await Article.countDocuments({ isPremium: false });
        const byCategory = await Article.aggregate([
            { $group: { _id: '$category', count: { $sum: 1 } } },
            { $sort: { _id: 1 } },
        ]);
        console.log(`   Total: ${total} | Premium: ${premium} | Free: ${free}`);
        byCategory.forEach((c) => console.log(`   ${c._id}: ${c.count}`));

        await mongoose.disconnect();
        console.log('\n🎉 Seeding complete!');
        process.exit(0);
    } catch (err) {
        console.error('❌ Seeding failed:', err);
        process.exit(1);
    }
}

seed();
